# Generated by Django 3.2.7 on 2021-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NON-BINARY', 'NON-BINARY'), ('TRANSGENDER', 'TRANSGENDER')], default='FEMALE', max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(default='Nairobi', max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('joining_date', models.DateField(null=True)),
                ('contract', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('resume', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('course_name', models.CharField(max_length=20)),
                ('salary', models.BigIntegerField(null=True)),
            ],
        ),
    ]
