# Generated by Django 3.2.7 on 2021-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(default='yyyy-mm-dd', null=True),
        ),
    ]
